gui: 
    theme:
        selectedLineBgColor: 
            - underline
        selectedRangeBgColor: 
            - underline

    showIcons: true
    expandFocusedSidePanel: true
git:
    paging:
        colorArg: always
        pager: delta --dark --paging=never
