gui: 
    theme:
        selectedLineBgColor: 
            - underline
        selectedRangeBgColor: 
            - underline

    expandFocusedSidePanel: true
    nerdFontsVersion: "3"
git:
    paging:
        colorArg: always
        pager: delta --dark --paging=never
