# set the default editor. Is used for aliases 
export EDITOR="$(which nvim)"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
    colored-man-pages
    git
    pip
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-z
)

source $ZSH/oh-my-zsh.sh
source $ZSH/custom/plugins/forgit/forgit.plugin.zsh
source $ZSH/custom/plugins/zsh-interactive-cd/zsh-interactive-cd.plugin.zsh
source $ZSH_DOT_DIR/zsh_aliases
source $ZSH_DOT_DIR/p10k.zsh

# change the foreground color to black for the ls command
LS_COLORS=$LS_COLORS:'ow=30;42'; export LS_COLORS

# Zsh plugin key bindings
# accept the suggestion 
bindkey '^l' autosuggest-accept

# export FZF_DEFAULT_COMMAND='ag'
export FZF_DEFAULT_OPTS="--layout=reverse --inline-info"

# virtualenvwrapper settings
export WORKON_HOME=${XDG_DATA_HOME:-$HOME}/.virtualenvs
export PROJECT_HOME=${XDG_DATA_HOME:-$HOME}/Devel
export VIRTUALENVWRAPPER_PYTHON=$(which python3)
export VIRTUALENVWRAPPER_VIRTUALENV=~/.local/bin/virtualenv
source ~/.local/bin/virtualenvwrapper.sh

function fcat {
    cat $1 | fzf -m | while read line; do eval $line; done
}
